#!/usr/bin/env bash
#
# CA360 — single-server install script (Ubuntu 24.04 LTS).
#
# Run with sudo from inside the cloned repo:
#     cd ~/ca360 && sudo bash install.sh
#
# Idempotent: re-run any time. Existing config / DB / secrets are kept.
# Generates fresh JWT_SECRET and MASTER_ENCRYPTION_KEY only on first run.
#
# What it does:
#   1.  System packages (Node 22, PostgreSQL 16, Nginx, Git, build tools)
#   2.  Postgres role + database (auto-generated password, saved to .env)
#   3.  backend/.env (auto-generated secrets if missing)
#   4.  npm install + prisma generate + prisma migrate deploy
#   5.  Seed first firm + admin user (only if DB is empty)
#   6.  Build backend (NestJS)
#   7.  Build frontend (Vite) → /var/www/ca360
#   8.  systemd unit for backend  → ca360-api.service
#   9.  Nginx site (HTTP only — run setup-domain.sh later for HTTPS)
#  10.  Daily pg_dump cron → /var/backups/ca360/

set -euo pipefail

# ─── Configuration ──────────────────────────────────────────────────
REPO_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
APP_USER="ca360"
APP_DIR="${REPO_DIR}"
WEB_ROOT="/var/www/ca360"
UPLOADS_DIR="/var/lib/ca360/uploads"
BACKUP_DIR="/var/backups/ca360"
NODE_MAJOR="22"

# ─── Helpers ────────────────────────────────────────────────────────
log()  { echo -e "\n\033[1;36m==> $*\033[0m"; }
warn() { echo -e "\033[1;33m!! $*\033[0m"; }
fail() { echo -e "\033[1;31mxx $*\033[0m"; exit 1; }

# ─── Pre-flight ─────────────────────────────────────────────────────
[ "$EUID" = 0 ] || fail "Run with sudo: sudo bash install.sh"
[ -f "$REPO_DIR/backend/package.json" ] || fail "backend/package.json not found — run from the repo root"
[ -f "$REPO_DIR/frontend/package.json" ] || fail "frontend/package.json not found"

# Ubuntu version sanity check
if [ -f /etc/os-release ]; then
  . /etc/os-release
  [ "$ID" = "ubuntu" ] || warn "Built for Ubuntu — $PRETTY_NAME may need adjustments"
fi

# ─── 1. System packages ─────────────────────────────────────────────
log "Installing system packages…"
export DEBIAN_FRONTEND=noninteractive
apt-get update -qq
apt-get install -y -qq \
  curl ca-certificates gnupg lsb-release \
  postgresql postgresql-contrib \
  nginx \
  git build-essential \
  cron rsync

# Node.js — install only if missing or older than required
if ! command -v node >/dev/null || [ "$(node -v 2>/dev/null | sed 's/v//' | cut -d. -f1)" -lt "$NODE_MAJOR" ]; then
  log "Installing Node.js ${NODE_MAJOR} LTS…"
  curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" | bash - >/dev/null
  apt-get install -y -qq nodejs
else
  log "Node.js $(node -v) already installed — skipping"
fi

# Stop services we'll reconfigure (safe even on first install)
systemctl stop ca360-api 2>/dev/null || true

# ─── 2. PostgreSQL setup ────────────────────────────────────────────
log "Configuring PostgreSQL…"
systemctl enable --now postgresql

# Create role + database if they don't exist. Generate a strong password the
# FIRST time only — keep the existing one if .env already has DATABASE_URL.
ENV_FILE="${APP_DIR}/backend/.env"
if [ -f "$ENV_FILE" ] && grep -q "^DATABASE_URL=" "$ENV_FILE"; then
  DB_PASSWORD="$(grep "^DATABASE_URL=" "$ENV_FILE" | sed -E 's|.*://ca360:([^@]+)@.*|\1|')"
  log "Reusing existing DB password from backend/.env"
else
  DB_PASSWORD="$(openssl rand -base64 24 | tr -d '/+=' | head -c 32)"
  log "Generated new DB password (will be saved to backend/.env)"
fi

sudo -u postgres psql -v ON_ERROR_STOP=1 <<SQL >/dev/null
DO \$\$ BEGIN
  IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = 'ca360') THEN
    CREATE ROLE ca360 LOGIN PASSWORD '${DB_PASSWORD}';
  ELSE
    ALTER ROLE ca360 WITH PASSWORD '${DB_PASSWORD}';
  END IF;
END \$\$;
SQL

sudo -u postgres psql -v ON_ERROR_STOP=1 -tAc \
  "SELECT 1 FROM pg_database WHERE datname = 'ca360'" | grep -q 1 || \
  sudo -u postgres createdb -O ca360 ca360

# ─── 3. Generate / preserve backend/.env ────────────────────────────
log "Configuring backend/.env…"
if [ ! -f "$ENV_FILE" ]; then
  JWT_SECRET="$(openssl rand -base64 48 | tr -d '\n')"
  MASTER_KEY="$(openssl rand -base64 32 | tr -d '\n')"
  cat > "$ENV_FILE" <<ENV
# Auto-generated by install.sh — keep this file safe (it contains secrets).
DATABASE_URL="postgresql://ca360:${DB_PASSWORD}@localhost:5432/ca360?schema=public"

NODE_ENV=production
PORT=3000
FRONTEND_URL=http://localhost

JWT_SECRET=${JWT_SECRET}
JWT_EXPIRES_IN=15m
JWT_REFRESH_EXPIRES_IN=7d

TOTP_ISSUER=CA360
MASTER_ENCRYPTION_KEY=${MASTER_KEY}

STORAGE_DRIVER=local
STORAGE_LOCAL_PATH=${UPLOADS_DIR}

# First-run seed (only used if the DB has no firm yet — safe to leave)
SEED_FIRM_NAME="G Gaurav & Associates"
SEED_ADMIN_EMAIL=admin@ca360.local
SEED_ADMIN_PASSWORD=Admin@12345
SEED_ADMIN_NAME="Managing Partner"
ENV
  chmod 600 "$ENV_FILE"
  log "Generated fresh secrets in $ENV_FILE"
else
  # Always sync DB password (in case it was rotated above)
  sed -i -E "s|^DATABASE_URL=.*|DATABASE_URL=\"postgresql://ca360:${DB_PASSWORD}@localhost:5432/ca360?schema=public\"|" "$ENV_FILE"
  # Make sure STORAGE_LOCAL_PATH points at the system uploads dir
  sed -i -E "s|^STORAGE_LOCAL_PATH=.*|STORAGE_LOCAL_PATH=${UPLOADS_DIR}|" "$ENV_FILE"
  log "Existing $ENV_FILE preserved (only DATABASE_URL synced)"
fi

# ─── 4. Filesystem dirs (uploads + backups) ─────────────────────────
log "Creating data directories…"
mkdir -p "$UPLOADS_DIR" "$BACKUP_DIR"
chown -R "$APP_USER:$APP_USER" "$UPLOADS_DIR" "$BACKUP_DIR"

# Repo dir owned by deploy user
chown -R "$APP_USER:$APP_USER" "$APP_DIR"

# ─── 5. npm install + Prisma + build (run as APP_USER) ──────────────
log "Installing backend dependencies…"
sudo -u "$APP_USER" -H bash -c "cd '$APP_DIR/backend' && npm install --no-audit --no-fund"

log "Generating Prisma client + applying migrations…"
sudo -u "$APP_USER" -H bash -c "cd '$APP_DIR/backend' && npx --no-install prisma generate"
sudo -u "$APP_USER" -H bash -c "cd '$APP_DIR/backend' && npx --no-install prisma migrate deploy"

# Seed first firm + admin only if DB is empty
HAS_FIRM=$(sudo -u postgres psql -tAd ca360 -c "SELECT 1 FROM ca_firm LIMIT 1" 2>/dev/null || echo "")
if [ -z "$HAS_FIRM" ]; then
  log "Seeding first firm + admin user (DB is empty)…"
  sudo -u "$APP_USER" -H bash -c "cd '$APP_DIR/backend' && npm run seed"
else
  log "Existing firm data found — skipping seed"
fi

log "Building backend…"
sudo -u "$APP_USER" -H bash -c "cd '$APP_DIR/backend' && npm run build"

log "Installing frontend dependencies + building…"
sudo -u "$APP_USER" -H bash -c "cd '$APP_DIR/frontend' && npm install --no-audit --no-fund"
sudo -u "$APP_USER" -H bash -c "cd '$APP_DIR/frontend' && npm run build"

# Copy built frontend to web root
log "Publishing frontend to ${WEB_ROOT}…"
mkdir -p "$WEB_ROOT"
rsync -a --delete "$APP_DIR/frontend/dist/" "$WEB_ROOT/"
chown -R www-data:www-data "$WEB_ROOT"

# ─── 6. systemd unit for the backend ────────────────────────────────
log "Installing systemd unit ca360-api…"
cat > /etc/systemd/system/ca360-api.service <<UNIT
[Unit]
Description=CA360 API (NestJS backend)
After=network.target postgresql.service
Wants=postgresql.service

[Service]
Type=simple
User=${APP_USER}
WorkingDirectory=${APP_DIR}/backend
EnvironmentFile=${APP_DIR}/backend/.env
ExecStart=/usr/bin/node dist/src/main.js
Restart=on-failure
RestartSec=5
StandardOutput=journal
StandardError=journal
LimitNOFILE=65536
NoNewPrivileges=true
PrivateTmp=true

[Install]
WantedBy=multi-user.target
UNIT

systemctl daemon-reload
systemctl enable --now ca360-api
sleep 2
if ! systemctl is-active --quiet ca360-api; then
  warn "ca360-api failed to start — see: journalctl -u ca360-api -n 50"
fi

# ─── 7. Nginx (HTTP only — SSL added later by setup-domain.sh) ──────
log "Configuring Nginx…"
cat > /etc/nginx/sites-available/ca360 <<NGINX
server {
    listen 80 default_server;
    listen [::]:80 default_server;
    server_name _;

    root ${WEB_ROOT};
    index index.html;

    client_max_body_size 30M;

    # API → backend
    location /api/ {
        proxy_pass http://127.0.0.1:3000;
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_read_timeout 60s;
    }

    # Static frontend (SPA fallback)
    location / {
        try_files \$uri \$uri/ /index.html;
    }

    # Long-cache hashed assets
    location /assets/ {
        expires 30d;
        add_header Cache-Control "public, immutable";
    }
}
NGINX

# Disable the default welcome page if it's still enabled
rm -f /etc/nginx/sites-enabled/default
ln -sf /etc/nginx/sites-available/ca360 /etc/nginx/sites-enabled/ca360
nginx -t
systemctl reload nginx

# ─── 8. Backup cron (daily pg_dump) ─────────────────────────────────
log "Configuring daily backup cron…"
cat > /usr/local/bin/ca360-backup.sh <<'BACKUP'
#!/usr/bin/env bash
# Daily DB dump + uploads tarball. Keeps 14 days of backups on disk.
set -euo pipefail
BACKUP_DIR=/var/backups/ca360
STAMP=$(date +%Y%m%d-%H%M%S)
mkdir -p "$BACKUP_DIR"
sudo -u postgres pg_dump -Fc -d ca360 > "$BACKUP_DIR/ca360-db-$STAMP.dump"
tar -czf "$BACKUP_DIR/ca360-uploads-$STAMP.tar.gz" -C /var/lib/ca360 uploads 2>/dev/null || true
# Prune anything older than 14 days
find "$BACKUP_DIR" -type f -mtime +14 -name 'ca360-*' -delete
BACKUP
chmod +x /usr/local/bin/ca360-backup.sh

cat > /etc/cron.d/ca360-backup <<CRON
# Daily CA360 backup at 02:30
30 2 * * * root /usr/local/bin/ca360-backup.sh >> /var/log/ca360-backup.log 2>&1
CRON

# ─── Done ───────────────────────────────────────────────────────────
SERVER_IP="$(curl -s -4 ifconfig.me || hostname -I | awk '{print $1}')"
cat <<DONE

──────────────────────────────────────────────────────────────────
  CA360 install complete.
──────────────────────────────────────────────────────────────────

  Backend:   http://${SERVER_IP}/api/health       (systemd: ca360-api)
  Frontend:  http://${SERVER_IP}/                 (Nginx site: ca360)

  First admin login (CHANGE THIS IMMEDIATELY after first sign-in):
    URL       http://${SERVER_IP}/login
    Email     admin@ca360.local
    Password  Admin@12345

  Next steps:
    1. Open the URL above and log in.
    2. Settings → change admin password to something only you know.
    3. (Recommended) point a domain at this server's IP and run:
           sudo bash setup-domain.sh your-domain.in
       That will install a Let's Encrypt SSL cert and switch
       the site to HTTPS.

  Useful commands:
    journalctl -u ca360-api -f          # tail backend logs
    systemctl restart ca360-api         # restart backend
    systemctl status nginx              # nginx status
    /usr/local/bin/ca360-backup.sh      # run backup now (test)

  Backups land in /var/backups/ca360 daily at 02:30.

──────────────────────────────────────────────────────────────────
DONE
